#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4211
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="Beheer_SitefinityDemo")]
	public partial class SFEstateDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertestate_ToolboxControl(estate_ToolboxControl instance);
    partial void Updateestate_ToolboxControl(estate_ToolboxControl instance);
    partial void Deleteestate_ToolboxControl(estate_ToolboxControl instance);
    #endregion
		
		public SFEstateDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["Beheer_SitefinityDemoConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SFEstateDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SFEstateDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SFEstateDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SFEstateDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<estate_ToolboxControl> estate_ToolboxControls
		{
			get
			{
				return this.GetTable<estate_ToolboxControl>();
			}
		}
	}
	
	[Table(Name="dbo.estate_ToolboxControls")]
	public partial class estate_ToolboxControl : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _id;
		
		private System.Nullable<System.Guid> _parent;
		
		private string _name;
		
		private bool _showControl;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(System.Guid value);
    partial void OnidChanged();
    partial void OnparentChanging(System.Nullable<System.Guid> value);
    partial void OnparentChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnshowControlChanging(bool value);
    partial void OnshowControlChanged();
    #endregion
		
		public estate_ToolboxControl()
		{
			OnCreated();
		}
		
		[Column(Storage="_id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[Column(Storage="_parent", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> parent
		{
			get
			{
				return this._parent;
			}
			set
			{
				if ((this._parent != value))
				{
					this.OnparentChanging(value);
					this.SendPropertyChanging();
					this._parent = value;
					this.SendPropertyChanged("parent");
					this.OnparentChanged();
				}
			}
		}
		
		[Column(Storage="_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[Column(Storage="_showControl", DbType="Bit NOT NULL")]
		public bool showControl
		{
			get
			{
				return this._showControl;
			}
			set
			{
				if ((this._showControl != value))
				{
					this.OnshowControlChanging(value);
					this.SendPropertyChanging();
					this._showControl = value;
					this.SendPropertyChanged("showControl");
					this.OnshowControlChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
